### PR TITLE
Fix: Correctly mention bot accounts in release notes

### LINKED ISSUE #60: Bot users don’t render quite right
It seems that bot users are inlined as usual, and count as contributors, which results in a bit of unusual rendering:

>* 7: Update dependency emoji-regex to v7.0.1 by @renovate[bot]
>
>Thanks to @renovate-bot, @renovate[bot] and @ticky!

### PR DESCRIPTION
**Pull request by jamietanna**
As noted in #60, bot accounts are currently being mis-mentioned, where
instead of linking through to `dependabot[bot]` it'll tag a user
`@dependabot` which isn't the same, and can result in unwanted
notifications.

To address this, we can retrieve the type of user that has authored a
Pull Request, looking at the `__typename` to determine if it's a `Bot`
or a `User` account, and provide a Markdown link to the Bot account's
app page.

Unfortunately this may result in a name such as:

@[dependabot[bot]](https://github.com/apps/dependabot)

But this is a better result than tagging the wrong account.

Closes #60.

### CODE REVIEW

**Review by justinmchase — APPROVED** [review]

File: lib/releases.js [hunk 1]
```diff
@@ -235,17 +241,26 @@ const generateChangeLog = (mergedPullRequests, config) => {
...
     pullRequests
-      .map((pullRequest) =>
-        template(config['change-template'], {
+      .map((pullRequest) => {
+        var pullAuthor = 'ghost'
+        if (pullRequest.author) {
+          pullAuthor =
+            pullRequest.author.__typename &&
+            pullRequest.author.__typename === 'Bot'
+              ? `[${pullRequest.author.login}[bot]](${pullRequest.author.url})`
```
Comment (CFenner) [inline lib/releases.js:250]:
```suggestion
              ? `[@${pullRequest.author.login}[bot]](${pullRequest.author.url})`
```

File: lib/releases.js [hunk 2]
```diff
@@ -111,7 +111,13 @@ const contributorsSentence = ({ commits, pullRequests, config }) => {
       pullRequest.author &&
       !excludeContributors.includes(pullRequest.author.login)
     ) {
-      contributors.add(`@${pullRequest.author.login}`)
+      if (pullRequest.author.__typename === 'Bot') {
+        contributors.add(
+          `[${pullRequest.author.login}[bot]](${pullRequest.author.url})`
```
Comment (CFenner) [inline lib/releases.js:116]:
```suggestion
          `[@${pullRequest.author.login}[bot]](${pullRequest.author.url})`
```

File: lib/releases.js [hunk 3]
```diff
@@ -111,7 +111,13 @@ const contributorsSentence = ({ commits, pullRequests, config }) => {
       pullRequest.author &&
       !excludeContributors.includes(pullRequest.author.login)
     ) {
-      contributors.add(`@${pullRequest.author.login}`)
+      if (pullRequest.author.__typename === 'Bot') {
```
Comment (CFenner) [inline lib/releases.js:114]: Is the author url set also for human users? Then we could omit the else case.

**Review by CFenner — APPROVED** [review]
👍

File: lib/releases.js (hunk 3 above)
Comment (jetersen) [reply lib/releases.js:114]: URL is always set.

**Comment by jamietanna** [comment]
Thank you 🙇

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
@jamietanna Thank you for the contribution :clap:
