### PR TITLE
Fix overlapping label categorization

### LINKED ISSUE #293: Category with multiple labels produces a header per label
Using the latest (`v5.2.0`) as a GitHub Action in my repo's workflow, I am seeing adverse behavior from #219 

My `release-drafter.yml` configuration file:

```yaml
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠️ Maintenance'
    labels:
      - 'maintenance'
      - 'dependencies'
template: |
  ## What's Changed

  $CHANGES
``` 

Notice that the category with the title "Maintenance" has 2 labels under it: "maintenance" and "dependencies".

When I have a Draft Release open that features merged PRs from _each_ of those labels, the Draft Release contents end up with a duplicate header:

image

### LINKED ISSUE #403: Multiple labels not grouping under one heading
Expected behavior: If there are multiple labels under one grouping, they are expected to be grouped under that heading.
Actual behavior: The heading is being repeated for each label under that title/heading.

Screenshots:
Config file:
Screen Shot 2020-01-29 at 1 40 53 PM

Result:
Screen Shot 2020-01-29 at 1 31 40 PM

The above have labels bug, bugfix, and sentry respectively.

### PR DESCRIPTION
**Pull request by casz**
resolves #293
resolves #403

This should fix categorization overlapping. I'd like to have someone review the code around the looping. Wonder if we could optimize the looping.

I'd like to avoid using `reduce` as I feel it makes this area of the code particular hard to read 😅

### CODE REVIEW

File: lib/releases.js [hunk 1]
```diff
@@ -80,74 +80,86 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
+
+  const filterUncategorized = category => category.title !== UNCATEGORIZED
+
+  // we only want pull requests that have yet to be categorized
+  const uncategorizedPullRequests = pullRequests
+    .map(filterPullRequests)
+    .filter(Boolean)
+
+  orderedCategories.filter(filterUncategorized).map(category => {
+    uncategorizedPullRequests.map(pullRequest => {
```
Comment (casz) [inline lib/releases.js]: Perhaps there is a better way to achieve this without looping over each pull request for each category.

File: lib/releases.js [hunk 2]
```diff
@@ -80,74 +80,86 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
 
-const categorizePullRequests = (pullRequests, categories, excludeLabels) => {
-  return pullRequests.reduce(
-    (acc, pullRequest) => {
+const categorizePullRequests = (
+  pullRequests,
+  orderedCategories,
+  excludeLabels
+) => {
+  const categories = [...orderedCategories.flatMap(category => category.labels)]
```
Comment (casz) [inline lib/releases.js]:
```suggestion
  const categoryList = orderedCategories.flatMap(category => category.labels)
```

File: lib/releases.js [hunk 3]
```diff
@@ -80,74 +80,86 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
+      return null
+    }
+    return pullRequest
+  }
+
+  const filterUncategorized = category => category.title !== UNCATEGORIZED
+
+  // we only want pull requests that have yet to be categorized
+  const uncategorizedPullRequests = pullRequests
+    .map(filterPullRequests)
```
Comment (casz) [inline lib/releases.js]: for some reason I cannot pass this to filter and inside the `filterPullRequests` pass true or false back.

File: test/index.test.js [hunk 4]
```diff
@@ -669,6 +669,122 @@ Previous tag: ''
...
+          .reply(
+            200,
+            require('./fixtures/__generated__/graphql-commits-overlapping-label.json')
+          )
+
+        nock('https://api.github.com')
+          .post(
+            '/repos/toolmantim/release-drafter-test-project/releases',
+            body => {
+              expect(body).toMatchInlineSnapshot(`
```
Comment (casz) [inline test/index.test.js]: We should use `toMatchInlineSnapshot` for all our other inline matching 😅

**Comment by casz** [comment]
Would appreciate a reviews from @JamesMGreene @TimonVS 🙇

File: lib/releases.js [hunk 5]
```diff
@@ -80,74 +79,84 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
+
+  return categoriesConfig.map(category => {
+    if (!category.labels) category.labels = []
+    if (category.label) {
+      // treat label as labels
+      category.labels.push(category.label)
+      delete category.label
+    }
+    return { ...category, pullRequests: [] }
+  })
```
Comment (TimonVS) [inline lib/releases.js]: This should probably be part of the config validation. Can you move this to `config.js` or `schema.js` as `validateCategoriesConfig` or `normalizeCategoriesConfig`?

File: lib/releases.js [hunk 6]
```diff
@@ -80,74 +79,84 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
 }
 
-const categorizePullRequests = (pullRequests, categories, excludeLabels) => {
-  return pullRequests.reduce(
-    (acc, pullRequest) => {
+const categorizePullRequests = (
+  pullRequests,
+  orderedCategories,
```
Comment (TimonVS) [inline lib/releases.js]:
```suggestion
  categoriesConfig,
```

File: lib/releases.js [hunk 7]
```diff
@@ -80,74 +79,84 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
+  excludeLabels
+) => {
+  const categories = orderedCategories.flatMap(category => category.labels)
```
Comment (TimonVS) [inline lib/releases.js]: Categories and labels are not the same thing. I'm not sure if my suggestion is the best name, but something along these lines would be an improvement.

```suggestion
  const allCategoryLabels = orderedCategories.flatMap(category => category.labels)
```

File: lib/releases.js [hunk 8]
```diff
@@ -80,74 +79,84 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
+  const filterPullRequests = pullRequest => {
+    const labels = pullRequest.labels.nodes
+
+    if (labels.some(label => excludeLabels.includes(label.name))) {
+      return false
+    } else if (
+      labels.length === 0 ||
+      !labels.some(label => categories.includes(label.name))
+    ) {
+      orderedCategories[0].pullRequests.push(pullRequest)
```
Comment (TimonVS) [inline lib/releases.js]: 1. We shouldn't mutate inputs as that can cause subtle bugs.
2. This can cause bugs when we decide to change the order of uncategorized PRs. Can you push these to a separate array?

File: lib/releases.js [hunk 9]
```diff
@@ -80,74 +79,84 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
-    (acc, pullRequest) => {
+const categorizePullRequests = (
+  pullRequests,
+  orderedCategories,
+  excludeLabels
+) => {
+  const categories = orderedCategories.flatMap(category => category.labels)
+
+  // exclude pull requests with exclude labels first than push any uncategorized pull requests to UNCATEGORIZED category
+  const filterPullRequests = pullRequest => {
```
Comment (TimonVS) [inline lib/releases.js]: The comment describes what the function is doing. I prefer to only have comments to describe the "why". If we encode this in the name of the function, the comment becomes unnecessary. In order to do this we must first make this function responsible for one thing: `filterExcludedPullRequests`. We can create a second function which is responsible for putting uncategorized PRs in a separate array.

File: lib/releases.js [hunk 10]
```diff
@@ -80,74 +79,84 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
-      ) {
-        acc[UNCATEGORIZED].push(pullRequest)
-      } else {
-        labels.forEach(label => {
-          if (!acc[label.name]) acc[label.name] = []
-
-          acc[label.name].push(pullRequest)
-        })
+      if (labels.some(label => category.labels.includes(label.name))) {
+        category.pullRequests.push(pullRequest)
```
Comment (TimonVS) [inline lib/releases.js]: Also here we shouldn't mutate the input :)
We can create a new array which contains the results.

File: lib/releases.js (hunk 5 above)
Comment (casz) [reply lib/releases.js]: Yes schema can totally take care of most of it.

Now the function only handles unwrapping categories into allCategoryLabels, orderedCategories

Comment (casz) [reply lib/releases.js]: The label to labels and making sure it is an array has moved to schema.json

File: lib/releases.js (hunk 9 above)
Comment (casz) [reply lib/releases.js]: I'd like to avoid looping over the same thing too many times 😓 But that's just me.

File: lib/releases.js (hunk 10 above)
Comment (casz) [reply lib/releases.js]: Created a new array.

File: lib/releases.js (hunk 8 above)
Comment (casz) [reply lib/releases.js]: created a separate array

**Comment by casz** [comment]
Any chance we can get this merged? We have plenty of open pull requests. 😅

File: test/index.test.js (hunk 4 above)
Comment (TimonVS) [reply test/index.test.js]: That's a great idea!

File: lib/releases.js [hunk 11]
```diff
@@ -79,91 +78,95 @@ const contributorsSentence = ({ commits, pullRequests }) => {
...
+
+  // we only want pull requests that have yet to be categorized
+  const filteredPullRequests = pullRequests
+    .filter(filterExcludedPullRequests)
+    .filter(filterUncategorizedPullRequests)
+
+  categorizedPullRequests.map(category => {
+    filteredPullRequests.map(pullRequest => {
+      // lets categorize some pull request based on labels
+      // due note that having the same label in multiple categories
```
Comment (TimonVS) [inline lib/releases.js]:
```suggestion
      // note that having the same label in multiple categories
```

**Comment by casz** [comment]
👏 Thanks @TimonVS

**Comment by oleg-nenashev** [comment]
Uh, I was actually using the label duplication in order to simplify splitting multi-entry changelogs. E.g. see https://github.com/jenkinsci/plugin-pom/pull/271 where I inject two entries into PR title and put two labels categorizing each of them. Then I just copy-edit the release draft 

Mandatory XKCD comics for such comment:

image

https://xkcd.com/1172/

**Comment by casz** [comment]
Should be fairly simple to add a condition enables it again.

**Comment by Jetersen** [comment]
@oleg-nenashev btw that case is still supported. We loop over each category so if a PR has multiple labels that land into multiple categories you still get the PR duplicated.

Also clearly noted in my code comment:
https://github.com/release-drafter/release-drafter/blob/ec0f2c5e261a34c78e21e978fedac2810daf2165/lib/releases.js#L116-L126

**Comment by Jetersen** [comment]
@oleg-nenashev btw that case is still supported. We loop over each category so if a PR has multiple labels that land into multiple categories you still get the PR duplicated.

Also clearly noted in my code comment:
https://github.com/release-drafter/release-drafter/blob/ec0f2c5e261a34c78e21e978fedac2810daf2165/lib/releases.js#L116-L126

The duplication we removed was when multiple labels was added to multiple categories.

So for instance with the following config:
```yaml
categories:
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
```
a PR with the labels `bug` and `fix` would previously \
be duplicated twice inside the same `🐛 Bug Fixes` category

Now with this PR it will only be included once

**Comment by Jetersen** [comment]
perhaps the comment should be updated with or duplicated if a pr has multiple labels in multiple categories.

**Comment by jetersen** [comment]
@timja this PR should fix the bug you experienced in slack plugin:
image
https://github.com/jenkinsci/slack-plugin/pull/675
https://github.com/jenkinsci/slack-plugin/pull/682


as `bug` and `fix` this made it "duplicated" in the same category which this PR fixes.

Hopefully that makes the case clearer @oleg-nenashev for when the bug will occur.

if a PR has multiple labels that fit into multiple categories, that is not considered as duplication.

@TimonVS @toolmantim would appreciate a release 😅

**Comment by ssbarnea** [comment]
As this was finally fixed, how long should we wait till this will reach the app at https://github.com/apps/release-drafter ? That bug is making the result really ugly https://github.com/ansible-community/molecule/releases

**Comment by jetersen** [comment]
@ssbarnea finally got access to heroku and npm :)
So I managed to deploy a new version of the probot app.
